kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.todoapp.deployment.template.spec.serviceAccountName }}
  namespace: mateapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mateapp
  name: {{ .Values.todoapp.deployment.template.spec.serviceAccountName }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.todoapp.deployment.template.spec.serviceAccountName }}-binding
  namespace: mateapp
subjects:
- kind: ServiceAccount
  name: {{ .Values.todoapp.deployment.template.spec.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.todoapp.deployment.template.spec.serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io